version: "3.8"

services:
  postgres:
    container_name: database
    image: postgres:13-alpine
    # restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfoliodb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build:
      context: backend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - "./backend/:/src"
      # - "/src/node_modules/"
    command: npm run start:dev
    ports:
      - "5000:3000"
    # tty: true
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  frontend:
    ports:
      - 3001:3000
    build:
      context: frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    #   - /usr/src/app/.next
