version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    # restart: always
    volumes:
      - ./docker/db/data:${PGDATA:-/var/lib/postgresql/data}
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      # POSTGRES_DB: db
    ports:
      - 5432:5432
  backend:
    build:
      context: backend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/src
    command: npm run start:dev
    ports:
      - "5000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      DB_SCHEMA: postgres
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: postgres
  frontend:
    ports:
      - 3001:3000
    build:
      context: frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    #   - /usr/src/app/.next

networks:
  portfolio:
    driver: bridge